### ISSUE TITLE
Help!Help

### ISSUE THREAD

**Issue by ThanhPham1987** [Talgin/stream_worker#1]
Hi Talgin,
Please tell me requirement package for this code.
Best regards,
PeterPham

**Comment by Talgin** [comment]
Main packages:
imutils
numpy
mxnet
scikit-learn
scikit-image
opencv-python
If you encounter bbox.so missing error, remove the rcnn folder and download from https://github.com/deepinsight/insightface/tree/master/RetinaFace rcnn folder. Then enter the rcnn/cython and do: 
python setup.py build_ext --inplace

**Comment by Talgin** [comment]
I think this issue can be closed now.
